[package]
name = "mircmd"
version = "0.3.0"
description = "A modern, powerful graphical user interface for molecular structure modeling."
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.5.3", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9.34"
serde_with = "3.16.1"
tauri = { version = "2.9.5", features = [] }
tauri-plugin-log = "2"
anyhow = "1.0.100"
clap = { version = "4.5.53", features = ["derive"] }
directories = "6.0.0"
rolling-file = "0.2.0"
tracing = "0.1.44"
tracing-appender = "0.2.4"
tracing-subscriber = { version = "0.3.22", features = [
    "env-filter",
    "fmt",
    "time",
    "local-time",
] }
time = { version = "0.3.44", features = [
    "macros",
    "formatting",
    "local-offset",
] }
wasmtime = "40.0.1"
wasmtime-wasi = "40.0.1"
wit-bindgen = "0.50.0"
uuid = { version = "1.19.0", features = ["v7", "serde"] }
tauri-plugin-dialog = "2.6.0"

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
