[project]
name = "mir-commander"
description = "A modern, powerful graphical user interface for molecular structure modeling."
license-files = ["resources/policy/LICENSE.txt"]
requires-python = ">=3.14.5, <4"
dependencies = [
    "mir-commander-file-importer-host",
    "httpx~=0.28.1",
    "numpy~=2.5.3",
    "pillow~=12.3.0",
    "pydantic~=2.13.0",
    "pydantic-extra-types~=2.11.1",
    "pyopengl~=3.1.10",
    "pyopengl-accelerate~=3.1.10",
    "pyside6-essentials~=6.11.2",
    "pyyaml~=6.0.3",
    "wasmtime~=49.0.0",
]
dynamic = ["version"]

[project.scripts]
mircmd = "mir_commander.__main__:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "cython~=3.3.0",
    "setuptools~=84.0.0",
    "mypy~=2.3.1",
    "pre-commit~=4.6.2",
    "pre-commit-hooks~=6.0.0",
    "pytest~=9.1.1",
    "pytest-cov~=7.1.0",
    "ruff~=0.16.9",
    "types-pyyaml~=6.0.12.20260906",
    "cx-freeze~=8.7.1",
]

[tool.uv]

[tool.uv.sources]
mir-commander-file-importer-host = { path = "mir_commander_file_importer_host" }

[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[tool.hatch.version]
path = "mir_commander/__init__.py"

[tool.setuptools]
py-modules = []

[tool.setuptools.dynamic]
version = { attr = "mir_commander.__version__" }

[tool.mypy]
ignore_missing_imports = true
check_untyped_defs = true
explicit_package_bases = true

[tool.ruff]
line-length = 120
target-version = "py312"
exclude = [".venv", "tmp"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[[tool.cxfreeze.executables]]
script = "mir_commander/__main__.py"
base = "gui"
target_name = "mircmd"
icon = "resources/building/icon"
shortcut_name = "Mir Commander"
shortcut_dir = "StartMenuFolder"

[tool.cxfreeze.build_exe]
packages = [
    "mir_commander",
    # the following packages are required by plugins
    "httpx",
    "PIL",
    "pydantic_extra_types",
    # the following packages can't automatically be found by cxfreeze
    "logging",
    "OpenGL",
    "PySide6.QtOpenGLWidgets",
    "numpy",
    "numpy.__init__",
    "numpy.f2py",
    "numpy.testing",
]
excludes = ["cython", "pytest", "setuptools", "tkinter"]
include_files = [
    [
        "resources/policy/LICENSE.txt",
        "LICENSE.txt",
    ],
    [
        "resources/resources.rcc",
        "resources/resources.rcc",
    ],
    [
        "build/lib/plugins",
        "plugins",
    ],
    [
        "plugins/builtin/file_exporters/loader.py",
        "plugins/builtin/file_exporters/loader.py",
    ],
    [
        "plugins/builtin/file_importers/loader.py",
        "plugins/builtin/file_importers/loader.py",
    ],
    [
        "plugins/builtin/programs/loader.py",
        "plugins/builtin/programs/loader.py",
    ],
    [
        "plugins/builtin/project_nodes/loader.py",
        "plugins/builtin/project_nodes/loader.py",
    ],
    [
        "plugins/builtin/resources/loader.py",
        "plugins/builtin/resources/loader.py",
    ],
    [
        "plugins/builtin/resources/resources.rcc",
        "plugins/builtin/resources/resources.rcc",
    ],
]
include_msvcr = true

[tool.cxfreeze.bdist_mac]
bundle_name = "Mir Commander"
iconfile = "resources/building/icon.icns"
custom_info_plist = "resources/building/macos/Info.plist"

[tool.cxfreeze.bdist_msi]
all_users = true
initial_target_dir = "[ProgramFiles64Folder]Mir Commander"
install_icon = "resources/building/icon.ico"
target_name = "MirCommander"
launch_on_finish = true
