class ExportFormat:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def extensions(self) -> list[str]: ...
    @property
    def supported_node_types(self) -> list[str]: ...
    @property
    def settings_schema(self) -> str | None: ...

def formats(wasm_path: str) -> list[ExportFormat]: ...
def dump(wasm_path: str, data: bytes, format_id: str, settings: str, file_path: str) -> None: ...
